apiVersion: v1
kind: Service
metadata: 
  name: frontend-svc
  labels: 
    app: guestbook
    tier: frontend 
spec: 
  ports: 
  - port: 80
  type: LoadBalancer
  selector: 
    app: guestbook
    tier: frontend