apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
  namespace: dev
  labels:
    app: nginx
spec:
  clusterIP: None
  selector:
    app: nginx
    tier: frontend
  ports:
    - name: http
      port: 80
      targetPort: http
