apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: my-role
rules:
    # from where resources come (ex: pods come from apps)
  - apiGroups: [""]
    # On which resources
    resources: ["pods"]
    # What he can do
    verbs: ["get", "watch", "list"]

---
#------------------------------
#         Role
#------------------------------
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: test-role
rules:
  - apiGroups:
      - apps
    resources:
      - pods
    verbs:
      - get
      - watch
      - list