# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  # What we want to install
  config.vm.provision "shell", path: "bootstrap.sh"

  # Kubernetes Master Server
  config.vm.define "master" do |master|

    # OS which we are on
    master.vm.box = "centos/7"
    # Network Settings
    master.vm.hostname = "master.data.com"
    master.vm.network "private_network", ip: "172.42.42.100"
    master.vm.network "forwarded_port", guest: 80, host: 80
    # Provider
    master.vm.provider "virtualbox" do |v|
      v.name = "master"
      v.memory = 4048
      v.cpus = 4
      # Prevent VirtualBox from interfering with host audio stack
      v.customize ["modifyvm", :id, "--audio", "none"]
    end
    # What we want to install
    master.vm.provision "shell", path: "bootstrap_kmaster.sh"
  end

  NodeCount = 2

  # Kubernetes Worker Nodes
  (1..NodeCount).each do |i|
    config.vm.define "slave#{i}" do |workernode|
      workernode.vm.box = "centos/7"
      workernode.vm.hostname = "slave#{i}.data.com"
      workernode.vm.network "private_network", ip: "172.42.42.10#{i}"
      workernode.vm.provider "virtualbox" do |v|
        v.name = "slave#{i}"
        v.memory = 4048
        v.cpus = 1
        # Prevent VirtualBox from interfering with host audio stack
        v.customize ["modifyvm", :id, "--audio", "none"]
      end
      workernode.vm.provision "shell", path: "bootstrap_kworker.sh"
    end
  end

end