apiVersion: v1
kind: Service
metadata:
  name: {{ include "airflow.postgresql.fullname" . }}-svc
  labels:
    app: {{ include "airflow.labels.app" . }}
    release: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.postgresql.service.port }}
  selector:
    app: postgresql # todo