kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  #namespace: "airflow"
  name: pod-launcher-rolebinding
  labels:
    tier: airflow
    release: release-name
    chart: "airflow-1.5.0"
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-launcher-role
subjects:
  - kind: ServiceAccount
    name: airflow-scheduler
    #namespace: "airflow"