ingress:
  apiServer:
    enabled: true
    ingressClassName: alb
    path: /
    pathType: Prefix
    hosts:
      - name: airflow-student1.example.com
        tls:
          enabled: false
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
      alb.ingress.kubernetes.io/healthcheck-path: /health
