apiVersion: v1
kind: Pod
metadata:
  name: test-deploy

spec:
  containers:
    - image: nginx
      name: nginx
      volumeMounts:
        - name: test-volume
          mountPath: /path/to/folder

  volumes:
    - name: test-volume
      hostPath:
        # directory location on the host
        path: /home/massi/dev/kubernetes/volumes
        type: Directory



