apiVersion: apps/v1
kind: Deployment
metadata: 
  name: redis-master 
  labels: 
    app: redis
spec: 
  replicas: 1
  selector:
    matchLabels: 
    # must be the same an the label of template 
      app: redis
      # ?? 
      role: master
      # ?? 
      tier: backend  
  template: 
    metadata: 
      name: redis
      labels: 
        app: redis
        role: master
        tier: backend
    spec: 
      containers: 
      - name: master
        image: k8s.gcr.io/redis:e2e
        # ??
        resources:
          requests: 
            cpu: 100m
            memory: 100Mi
        ports: 
        - containerPort: 6379