# ======================================================================
#                               Services
# ======================================================================
# Service NodePort to expose port 32080 to external
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default.Chart.Name }} #airflow-svc
  labels:
    app: airflow-app
spec:
  type: NodePort
  selector:
    app: airflow-app
  ports:
    - name: airflow-port
      protocol: TCP
      # name of port exposed by the container
      targetPort: airflow-port
      # node exposed by service in internal
      port: 8080
      # node to expose to external
      nodePort: 32080

---
# Service ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: postgres-port
      targetPort: postgres-port
      port: 5432