apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sngix
  name: sngix
spec:
  containers:
  - image: nginx
    name: sngix
    env: 
    # load secret by key
    - name: USERNAME
      valueFrom: 
        secretKeyRef:
            name: mysecret2
            key: username
    # mount the secret from the volume
    volumeMounts: 
      - name: foo
        mountPath: secret/path
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes: 
    # add the secret in the volume
   - name: foo
     secret: 
        secretName: mysecret2
        
