webServer:
  enabled: false
  image:
    repository: "puckel/docker-airflow"
    tag: "latest"

postgresql:
  replicaCount: 1
  dbName: postgresdb
  configMapName: postgres-config
  image:
    repository: postgres
    tag: latest
  service:
    port: 5432
    name: postgres-port
  storage:
    name: postgredb
    pvCapacity: 5Gi
    pvcStorageRequest: 5Gi
    path: /tmp/data/db/postgresql
  auth:
    username: airflow
    password: airflow

