apiVersion: v1
kind: Config
preferences: {}

clusters:
  - cluster:
      certificate-authority: kubelet.crt
      server: https://10.0.2.15:8443
    name: kubernetes

users:
  - name: john
    user:
      client-certificate: john.crt
      client-key: john.key

contexts:
  - context:
      cluster: kubernetes
      namespace: finance
      user: john
    name: john-kubernetes
current-context: ""

