kind: ServiceAccount
apiVersion: v1
metadata:
  name: airflow-scheduler
  labels:
    tier: airflow
    component: scheduler
    release: {{ .Release.Name }}
    #chart: "airflow-1.5.0"
    #heritage: Helm