apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-http
spec:
  containers:
  - name: liveness
    image: kubegoldenguide/question-thirteen
    livenessProbe:
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 6
      periodSeconds: 3

    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 10

