apiVersion: v1
kind: Service
metadata:
  name: {{ include "elk.name" . }}-kibana-svc
  namespace: {{ .Values.namespace.name }}
  release: {{ .Release.Name | quote }}
  labels:
    app: kibana
spec:
  selector:
    app: kibana
  ports:
    - port: {{ .Values.kibana.httpPort }}
      protocol: TCP 
      name: {{ .Values.kibana.httpPortName | default "http"}}
      targetPort: {{ .Values.kibana.targetPort }}
