apiVersion: v1
kind: Deployment 
metadata: 
  name: nginx-deploy
  labels: 
    app: nginx-app
spec: 
  replicas: 3
   # link between RS and Pods is by selector and labels 
  selector:
    # when have one value 
    matchLabels: 
        app: nginx-app
    matchExpressions: 
        - {key: tier, operator: In, values: [frontend]}
  # pods to run 
  template: 
    metadata: 
      labels: 
        app: nginx-app
        tier: frontend
    spec:
      containers: 
      - name: nginx-container
        image: nginx
        ports: 
          - containerPort: 80