apiVersion: v1
kind: ReplicationController
metadata: 
  # name of rc 
  name: nginx-rc
spec:
  # nb of replicas to have all time 
  replicas: 3
  # link between RC and Pods is by selector and labels 
  selector:
    app: nginx-app
  # pods to run 
  template: 
    metadata: 
      name: nginx-pod
      labels: 
        app: nginx-app
    spec:
      containers: 
      - name: nginx-container
        image: nginx
        ports: 
          - containerPort: 80