apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.postgresql.configMapName }}
  labels:
    app: {{ include "airflow.labels.app" . }}
data:
  POSTGRES_DB: {{ .Values.postgresql.dbName }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password  }}