apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
spec:
  # Applies to all containers inside the pod
  securityContext:
    # all process will be run with user ID 1000 (uid)
    runAsUser: 1000
    # gid
    runAsGroup: 3000
    # process are also part of supplementary group ID 2000
    fsGroup: 2000
  volumes:
  - name: sec-ctx-vol
    emptyDir: {}
  containers:
  - name: sec-ctx-demo
    image: busybox:1.28
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /data/demo
    securityContext:
      allowPrivilegeEscalation: false
