apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-every-five-minutes
  namespace: dev
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: hello
              image: busybox:1.36
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
              args:
                - date; echo "Hello from the Kubernetes cluster"
