apiVersion: batch/v1
kind: Job
metadata:
  name: count-to-six
  namespace: dev
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: counter
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
          args:
            - for i in 1 2 3 4 5 6; do echo "$i"; done
