apiVersion: v1
kind: Service
metadata:
  name: presto-cluster
  namespace: presto
spec:
  selector:
    app: presto-c
  ports:
  - name: p80
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30123
  - name: p3306
    port: 3306
    targetPort: 3306
  type: NodePort