apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-airflow
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/massi/kubernetes/volumes/airflow
    type: DirectoryOrCreate