apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test-clusterolebinding

roleRef:
  apiGroup: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  name: test-clusterole

subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: masters