apiVersion: v1
kind: Pod
metadata: 
  name: ngix-pod
  namespace: dev
  labels: 
    app: ngix
    tier: dev
spec: 
  containers: 
    - name: ngix-container
      image: ngix
      # port to expose
      ports:
        - name: test-port
          containerPort: 8080
          protocol: TCP
      # set env variables
      env:
        - name: test
          value: toto

      command: ["sh", "-c", "echo hello"]

      # where to mount the volume
      volumeMounts:
        - name: test-volume
          mountPath: /path/to/volume

  restartPolicy: Never

  # run the pods inside the node with label disktype: SSD
  nodeSelector:
    disktype: SSD

  # specify constraints based on the node labels
  affinity:
    nodeAffinity:
      # hard constraint
      # the constraint must be met during the scheduling
      requiredDuringSchedulingIgnoredDuringExecution:
        # pod can be placed inside the pod having the label 'kubernetes.io/e2e-az-name'
        # and whose values is either  'e2e-az1' or 'e2e-az2'
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/e2e-az-name
                operator: In
                values:
                  - e2e-az1
                  - e2e-az2
      # soft constraint
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: another-node-label-key
                operator: In
                values:
                  - another-node-label-value
  # What volumes to provide
  volumes:
    - name: test-volume
      awsElasticBlockStore:
        volumeID: my-id

